/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SchemeApplicationService } from "../schemeApplication.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SchemeApplicationCreateInput } from "./SchemeApplicationCreateInput";
import { SchemeApplication } from "./SchemeApplication";
import { SchemeApplicationFindManyArgs } from "./SchemeApplicationFindManyArgs";
import { SchemeApplicationWhereUniqueInput } from "./SchemeApplicationWhereUniqueInput";
import { SchemeApplicationUpdateInput } from "./SchemeApplicationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SchemeApplicationControllerBase {
  constructor(
    protected readonly service: SchemeApplicationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SchemeApplication })
  @nestAccessControl.UseRoles({
    resource: "SchemeApplication",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSchemeApplication(
    @common.Body() data: SchemeApplicationCreateInput
  ): Promise<SchemeApplication> {
    return await this.service.createSchemeApplication({
      data: {
        ...data,

        scheme: data.scheme
          ? {
              connect: data.scheme,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        documents: true,
        id: true,

        scheme: {
          select: {
            id: true,
          },
        },

        status: true,
        submittedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SchemeApplication] })
  @ApiNestedQuery(SchemeApplicationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SchemeApplication",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async schemeApplications(
    @common.Req() request: Request
  ): Promise<SchemeApplication[]> {
    const args = plainToClass(SchemeApplicationFindManyArgs, request.query);
    return this.service.schemeApplications({
      ...args,
      select: {
        createdAt: true,
        documents: true,
        id: true,

        scheme: {
          select: {
            id: true,
          },
        },

        status: true,
        submittedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SchemeApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SchemeApplication",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async schemeApplication(
    @common.Param() params: SchemeApplicationWhereUniqueInput
  ): Promise<SchemeApplication | null> {
    const result = await this.service.schemeApplication({
      where: params,
      select: {
        createdAt: true,
        documents: true,
        id: true,

        scheme: {
          select: {
            id: true,
          },
        },

        status: true,
        submittedAt: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SchemeApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SchemeApplication",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSchemeApplication(
    @common.Param() params: SchemeApplicationWhereUniqueInput,
    @common.Body() data: SchemeApplicationUpdateInput
  ): Promise<SchemeApplication | null> {
    try {
      return await this.service.updateSchemeApplication({
        where: params,
        data: {
          ...data,

          scheme: data.scheme
            ? {
                connect: data.scheme,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          documents: true,
          id: true,

          scheme: {
            select: {
              id: true,
            },
          },

          status: true,
          submittedAt: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SchemeApplication })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SchemeApplication",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSchemeApplication(
    @common.Param() params: SchemeApplicationWhereUniqueInput
  ): Promise<SchemeApplication | null> {
    try {
      return await this.service.deleteSchemeApplication({
        where: params,
        select: {
          createdAt: true,
          documents: true,
          id: true,

          scheme: {
            select: {
              id: true,
            },
          },

          status: true,
          submittedAt: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
